### ISSUE TITLE
Add conf_total_sessions_gauge (Sessions count)

### ISSUE THREAD

**Issue by diverser** [AndreyVMarkelov/prom-confluence-exporter#5]
Can you add new metric **conf_total_sessions_gauge** as it in jira exporter **jira_total_sessions_gauge**

**Comment by PatrickSchuster** [comment]
Hello,
I tried fixing this but I have difficulties with it. Jira's JiraUserSessionTracker easily provides this information. But so far, I couldn't find a similar way of doing so in Confluence. Maybe the developers of this plugin have an idea?

**Comment by diverser** [comment]
May be SQL query will help you ?

**Comment by AndreyVMarkelov** [comment]
Only way I found to iterate on users and check session each. No other way.

**Comment by AndreyVMarkelov** [comment]
@diverser Is it OK to have stats about count of users which has login in the 1h, 30h etc

**Comment by diverser** [comment]
Yes, let's try

**Comment by PatrickSchuster** [comment]
Thanks @AndreyVMarkelov , I was afraid that there was no "easy fix". I also asked a [similar question on Stackoverflow](https://stackoverflow.com/questions/48705895/visibility-of-confluence-user-sessions/48746933#48746933).
It seems to me that there is currently no elegant way of doing that in Confluence.

**Comment by AndreyVMarkelov** [comment]
@PatrickSchuster The best way here is use the same as https://github.com/AndreyVMarkelov/prom-confluence-exporter/blob/master/src/main/java/ru/andreymarkelov/atlas/plugins/promconfluenceexporter/manager/ScheduledMetricEvaluatorImpl.java

So, iterate by users and get loginInfo from loginManager and fll 2 metrics: logged before 3 hours and 24 hours

**Comment by AndreyVMarkelov** [comment]
Hi @diverser 
Done. See:
confluence_one_hour_active_users_gauge 1.0
confluence_today_active_users_gauge 1.0
